export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST'
export const ORDER_SUCCESS='ORDER_SUCCESS'
export const ORDER_FAIL='ORDER_FAIL'
export const ORDER_RESET='ORDER_RESET'
export const CART_EMPTY='CART_EMPTY'


export const ORDER_DETAILS_REQUEST='ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS='ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL='ORDER_DETAILS_FAIL'